name: Security Check

on:
  workflow_dispatch:
  schedule:
      - cron: 0 0 * * *

jobs:
  static-analysis:

    name: Security Checker

    runs-on: ubuntu-latest

    steps:
      - name: "📥 Fetch Repository Contents"
        uses: actions/checkout@v2

      - name: "💽  Installing PHP, Composer"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          ini-values: display_errors = on, error_reporting = E_ALL
          tools: composer

      - name: "💽  Installing Composer Packages"
        run: composer install

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Run Security Check
        uses: symfonycorp/security-checker-action@v4
